In [1]:
# import needed libraries
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter
import seaborn as sns
sns.set_style('darkgrid')

pd.set_option('display.max_columns', 50)

#### About Data
- `DatasetAfricaMalaria.csv` contains malaria incidents reports, cases reported among other data from 2007-2017, for 54 African countries. [Source](https://www.kaggle.com/datasets/lydia70/malaria-in-africa)

In [2]:
# load datasets
malaria = pd.read_csv("datasets/DatasetAfricaMalaria.csv")

In [3]:
# check first few rows of the data
malaria.head()

,Country Name,Year,Country Code,"Incidence of malaria (per 1,000 population at risk)",Malaria cases reported,Use of insecticide-treated bed nets (% of under-5 population),Children with fever receiving antimalarial drugs (% of children under age 5 with fever),Intermittent preventive treatment (IPT) of malaria in pregnancy (% of pregnant women),People using safely managed drinking water services (% of population),"People using safely managed drinking water services, rural (% of rural population)","People using safely managed drinking water services, urban (% of urban population)",People using safely managed sanitation services (% of population),"People using safely managed sanitation services, rural (% of rural population)","People using safely managed sanitation services, urban (% of urban population)",Rural population (% of total population),Rural population growth (annual %),Urban population (% of total population),Urban population growth (annual %),People using at least basic drinking water services (% of population),"People using at least basic drinking water services, rural (% of rural population)","People using at least basic drinking water services, urban (% of urban population)",People using at least basic sanitation services (% of population),"People using at least basic sanitation services, rural (% of rural population)","People using at least basic sanitation services, urban (% of urban population)",latitude,longitude,geometry
0,Algeria,2007,DZA,0.01,26.0,NaN,NaN,NaN,NaN,NaN,NaN,18.24,19.96,17.33,34.65,-0.60,65.35,2.71,91.68,85.83,94.78,85.85,76.94,90.57,28.033886,1.659626,POINT (28.033886 1.659626)
1,Angola,2007,AGO,286.72,1533485.0,18.0,29.8,1.5,NaN,NaN,NaN,NaN,NaN,NaN,42.48,1.91,57.52,5.01,47.96,23.77,65.83,37.26,14.00,54.44,-11.202692,17.873887,POINT (-11.202692 17.873887)
2,Benin,2007,BEN,480.24,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58.44,1.99,41.56,4.09,63.78,54.92,76.24,11.80,4.29,22.36,9.307690,2.315834,POINT (9.307689999999999 2.315834)
3,Botswana,2007,BWA,1.03,390.0,NaN,NaN,NaN,NaN,NaN,83.96,NaN,NaN,NaN,42.07,-1.44,57.93,4.80,78.89,57.60,94.35,61.60,39.99,77.30,-22.328474,24.684866,POINT (-22.328474 24.684866)
4,Burkina Faso,2007,BFA,503.80,44246.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.00,2.16,23.00,5.91,52.27,45.13,76.15,15.60,6.38,46.49,12.238333,-1.561593,POINT (12.238333 -1.561593)

In [4]:
malaria.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 594 entries, 0 to 593
Data columns (total 27 columns):
 #   Column                                                                                   Non-Null Count  Dtype
---  ------                                                                                   --------------  -----
 0   Country Name                                                                             594 non-null    object
 1   Year                                                                                     594 non-null    int64
 2   Country Code                                                                             594 non-null    object
 3   Incidence of malaria (per 1,000 population at risk)                                      550 non-null    float64
 4   Malaria cases reported                                                                   550 non-null    float64
 5   Use of insecticide-treated bed nets (% of under-5 population)                            132 non-null    float64
 6   Children with fever receiving antimalarial drugs (% of children under age 5 with fever)  122 non-null    float64
 7   Intermittent preventive treatment (IPT) of malaria in pregnancy (% of pregnant women)    106 non-null    float64
 8   People using safely managed drinking water services (% of population)                    99 non-null     float64
 9   People using safely managed drinking water services, rural (% of rural population)       88 non-null     float64
 10  People using safely managed drinking water services, urban (% of urban population)       176 non-null    float64
 11  People using safely managed sanitation services (% of population)                        132 non-null    float64
 12  People using safely managed sanitation services, rural (% of rural population)           110 non-null    float64
 13  People using safely managed sanitation services, urban  (% of urban population)          132 non-null    float64
 14  Rural population (% of total population)                                                 588 non-null    float64
 15  Rural population growth (annual %)                                                       588 non-null    float64
 16  Urban population (% of total population)                                                 588 non-null    float64
 17  Urban population growth (annual %)                                                       588 non-null    float64
 18  People using at least basic drinking water services (% of population)                    588 non-null    float64
 19  People using at least basic drinking water services, rural (% of rural population)       566 non-null    float64
 20  People using at least basic drinking water services, urban (% of urban population)       566 non-null    float64
 21  People using at least basic sanitation services (% of population)                        588 non-null    float64
 22  People using at least basic sanitation services, rural (% of rural population)           566 non-null    float64
 23  People using at least basic sanitation services, urban  (% of urban population)          566 non-null    float64
 24  latitude                                                                                 594 non-null    float64
 25  longitude                                                                                594 non-null    float64
 26  geometry                                                                                 594 non-null    object
dtypes: float64(23), int64(1), object(3)
memory usage: 125.4+ KB

In [5]:
# check percentage of missing data per column
malaria.isnull().mean() * 100

Country Name                                                                                0.000000
Year                                                                                        0.000000
Country Code                                                                                0.000000
Incidence of malaria (per 1,000 population at risk)                                         7.407407
Malaria cases reported                                                                      7.407407
Use of insecticide-treated bed nets (% of under-5 population)                              77.777778
Children with fever receiving antimalarial drugs (% of children under age 5 with fever)    79.461279
Intermittent preventive treatment (IPT) of malaria in pregnancy (% of pregnant women)      82.154882
People using safely managed drinking water services (% of population)                      83.333333
People using safely managed drinking water services, rural (% of rural population)         85.185185
People using safely managed drinking water services, urban (% of urban population)         70.370370
People using safely managed sanitation services (% of population)                          77.777778
People using safely managed sanitation services, rural (% of rural population)             81.481481
People using safely managed sanitation services, urban  (% of urban population)            77.777778
Rural population (% of total population)                                                    1.010101
Rural population growth (annual %)                                                          1.010101
Urban population (% of total population)                                                    1.010101
Urban population growth (annual %)                                                          1.010101
People using at least basic drinking water services (% of population)                       1.010101
People using at least basic drinking water services, rural (% of rural population)          4.713805
People using at least basic drinking water services, urban (% of urban population)          4.713805
People using at least basic sanitation services (% of population)                           1.010101
People using at least basic sanitation services, rural (% of rural population)              4.713805
People using at least basic sanitation services, urban  (% of urban population)             4.713805
latitude                                                                                    0.000000
longitude                                                                                   0.000000
geometry                                                                                    0.000000
dtype: float64

>Note: 
>- The data seem to provide needed information on malaria incidents and environmental factors
>- Remove columns with more than 50% missing values.

### Generating New Datasets?
The Child Health sheet shows more recent data than the Malaria in Africa dataset(2007-2017), but slightly different features and no data on environmental factors.

In [6]:
child_health_1 = pd.read_excel("datasets/Child-Health-Coverage-Database-December-2023.xlsx", sheet_name='ITN', skiprows = 4, header=[0,1])
child_health_2 = pd.read_excel("datasets/Child-Health-Coverage-Database-December-2023.xlsx", sheet_name='ITN2', skiprows = 4, header=[0,1])

In [7]:
# check first few rows of the data
child_health_1.head()

                 ISO Countries and areas          UNICEF Reporting Region  \
  Unnamed: 0_level_1  Unnamed: 1_level_1               Unnamed: 2_level_1
0                AFG         Afghanistan                       South Asia
1                AGO              Angola      Eastern and Southern Africa
2                AGO              Angola      Eastern and Southern Africa
3                AGO              Angola      Eastern and Southern Africa
4                AZE          Azerbaijan  Eastern Europe and Central Asia

  UNICEF Programme Region World Bank Income Group (2022)               Year  \
       Unnamed: 3_level_1             Unnamed: 4_level_1 Unnamed: 5_level_1
0                    ROSA                     Low income               2015
1                   ESARO            Lower middle income               2007
2                   ESARO            Lower middle income               2011
3                   ESARO            Lower middle income               2016
4                   ECARO            Upper middle income               2000

         Short Source                              Long Source  \
   Unnamed: 6_level_1                       Unnamed: 7_level_1
0            DHS 2015       Demographic and Health Survey 2015
1  Other NS 2006-2007                       Other NS 2006-2007
2            MIS 2011            Malaria Indicator Survey 2011
3       DHS 2015-2016  Demographic and Health Survey 2015-2016
4           MICS 2000   Multiple Indicator Cluster Survey 2000

            National   Sex         Area           WIQ                       \
  Unnamed: 8_level_1  Male Female Rural Urban Poorest Second Middle Fourth
0                4.6   NaN    NaN   4.2   6.1     1.1    3.3    5.5    6.8
1               18.0  18.0   18.0  19.0  17.0    17.0   16.0   22.0   17.0
2               25.9  25.4   26.4  24.4  28.9    11.7   17.9   23.4   31.0
3               21.7  21.1   22.2  19.7  23.0    16.8   23.1   23.9   23.0
4                1.0   2.0    1.0   2.0   1.0     2.0    2.0    2.0    NaN


  Richest
0     6.5
1    14.0
2    34.2
3    22.0
4     1.0

In [8]:
child_health_1.rename(columns=lambda x: x if not 'Unnamed' in str(x) else '', inplace=True)
child_health_1 = child_health_1.set_axis(['_'.join(c).strip('_') for c in child_health_1.columns], axis='columns')
child_health_1.head()

,ISO,Countries and areas,UNICEF Reporting Region,UNICEF Programme Region,World Bank Income Group (2022),Year,Short Source,Long Source,National,Sex_Male,Sex_Female,Area_Rural,Area_Urban,WIQ_Poorest,WIQ_Second,WIQ_Middle,WIQ_Fourth,WIQ_Richest
0,AFG,Afghanistan,South Asia,ROSA,Low income,2015,DHS 2015,Demographic and Health Survey 2015,4.6,NaN,NaN,4.2,6.1,1.1,3.3,5.5,6.8,6.5
1,AGO,Angola,Eastern and Southern Africa,ESARO,Lower middle income,2007,Other NS 2006-2007,Other NS 2006-2007,18.0,18.0,18.0,19.0,17.0,17.0,16.0,22.0,17.0,14.0
2,AGO,Angola,Eastern and Southern Africa,ESARO,Lower middle income,2011,MIS 2011,Malaria Indicator Survey 2011,25.9,25.4,26.4,24.4,28.9,11.7,17.9,23.4,31.0,34.2
3,AGO,Angola,Eastern and Southern Africa,ESARO,Lower middle income,2016,DHS 2015-2016,Demographic and Health Survey 2015-2016,21.7,21.1,22.2,19.7,23.0,16.8,23.1,23.9,23.0,22.0
4,AZE,Azerbaijan,Eastern Europe and Central Asia,ECARO,Upper middle income,2000,MICS 2000,Multiple Indicator Cluster Survey 2000,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,NaN,1.0

In [9]:
child_health_2.rename(columns=lambda x: x if not 'Unnamed' in str(x) else '', inplace=True)
child_health_2 = child_health_2.set_axis(['_'.join(c).strip('_') for c in child_health_2.columns], axis='columns')
child_health_2.head()

,ISO,Countries and areas,UNICEF Reporting Region,UNICEF Programme Region,World Bank Income Group (2022),Year,Short Source,Long Source,National,Area_Rural,Area_Urban,WIQ_Poorest,WIQ_Second,WIQ_Middle,WIQ_Fourth,WIQ_Richest
0,AFG,Afghanistan,South Asia,ROSA,Low income,2015,DHS 2015,Demographic and Health Survey 2015,2.9,3.3,1.8,1.9,3.0,4.0,3.8,1.8
1,AGO,Angola,Eastern and Southern Africa,ESARO,Lower middle income,2016,DHS 2015-2016,Demographic and Health Survey 2015-2016,12.5,13.2,12.0,11.0,14.6,13.3,10.8,12.2
2,BDI,Burundi,Eastern and Southern Africa,ESARO,Low income,2010,DHS 2010,Demographic and Health Survey 2010,22.1,21.5,28.3,19.2,21.7,23.3,21.1,26.3
3,BDI,Burundi,Eastern and Southern Africa,ESARO,Low income,2012,MIS 2012,Malaria Indicator Survey 2012,28.6,28.1,33.8,25.9,29.4,28.6,28.3,31.7
4,BEN,Benin,West and Central Africa,WCARO,Lower middle income,2012,DHS 2011-2012,Demographic and Health Survey 2011-2012,45.7,45.0,46.6,45.7,44.0,42.9,43.6,51.5

In [10]:
child_health_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 258 entries, 0 to 257
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   ISO                             258 non-null    object
 1   Countries and areas             258 non-null    object
 2   UNICEF Reporting Region         258 non-null    object
 3   UNICEF Programme Region         258 non-null    object
 4   World Bank Income Group (2022)  258 non-null    object
 5   Year                            258 non-null    int64
 6   Short Source                    258 non-null    object
 7   Long Source                     258 non-null    object
 8   National                        256 non-null    float64
 9   Sex_Male                        233 non-null    float64
 10  Sex_Female                      233 non-null    float64
 11  Area_Rural                      241 non-null    float64
 12  Area_Urban                      245 non-null    float64
 13  WIQ_Poorest                     225 non-null    float64
 14  WIQ_Second                      225 non-null    float64
 15  WIQ_Middle                      226 non-null    float64
 16  WIQ_Fourth                      228 non-null    float64
 17  WIQ_Richest                     231 non-null    float64
dtypes: float64(10), int64(1), object(7)
memory usage: 36.4+ KB

In [11]:
# check percentage of missing data per column
child_health_1.isnull().mean() * 100

ISO                                0.000000
Countries and areas                0.000000
UNICEF Reporting Region            0.000000
UNICEF Programme Region            0.000000
World Bank Income Group (2022)     0.000000
Year                               0.000000
Short Source                       0.000000
Long Source                        0.000000
National                           0.775194
Sex_Male                           9.689922
Sex_Female                         9.689922
Area_Rural                         6.589147
Area_Urban                         5.038760
WIQ_Poorest                       12.790698
WIQ_Second                        12.790698
WIQ_Middle                        12.403101
WIQ_Fourth                        11.627907
WIQ_Richest                       10.465116
dtype: float64

## 2. Data Processing
- Remove columns with more than 50% missing values

In [12]:
col_grt_50_missing = malaria.columns[((malaria.isnull().mean() * 100) < 50)]
malaria_final = malaria[col_grt_50_missing]

print(malaria_final.shape)
malaria_final.head()

(594, 18)

,Country Name,Year,Country Code,"Incidence of malaria (per 1,000 population at risk)",Malaria cases reported,Rural population (% of total population),Rural population growth (annual %),Urban population (% of total population),Urban population growth (annual %),People using at least basic drinking water services (% of population),"People using at least basic drinking water services, rural (% of rural population)","People using at least basic drinking water services, urban (% of urban population)",People using at least basic sanitation services (% of population),"People using at least basic sanitation services, rural (% of rural population)","People using at least basic sanitation services, urban (% of urban population)",latitude,longitude,geometry
0,Algeria,2007,DZA,0.01,26.0,34.65,-0.60,65.35,2.71,91.68,85.83,94.78,85.85,76.94,90.57,28.033886,1.659626,POINT (28.033886 1.659626)
1,Angola,2007,AGO,286.72,1533485.0,42.48,1.91,57.52,5.01,47.96,23.77,65.83,37.26,14.00,54.44,-11.202692,17.873887,POINT (-11.202692 17.873887)
2,Benin,2007,BEN,480.24,0.0,58.44,1.99,41.56,4.09,63.78,54.92,76.24,11.80,4.29,22.36,9.307690,2.315834,POINT (9.307689999999999 2.315834)
3,Botswana,2007,BWA,1.03,390.0,42.07,-1.44,57.93,4.80,78.89,57.60,94.35,61.60,39.99,77.30,-22.328474,24.684866,POINT (-22.328474 24.684866)
4,Burkina Faso,2007,BFA,503.80,44246.0,77.00,2.16,23.00,5.91,52.27,45.13,76.15,15.60,6.38,46.49,12.238333,-1.561593,POINT (12.238333 -1.561593)

In [14]:
malaria_final.isnull().mean() * 100

Country Name                                                                          0.000000
Year                                                                                  0.000000
Country Code                                                                          0.000000
Incidence of malaria (per 1,000 population at risk)                                   7.407407
Malaria cases reported                                                                7.407407
Rural population (% of total population)                                              1.010101
Rural population growth (annual %)                                                    1.010101
Urban population (% of total population)                                              1.010101
Urban population growth (annual %)                                                    1.010101
People using at least basic drinking water services (% of population)                 1.010101
People using at least basic drinking water services, rural (% of rural population)    4.713805
People using at least basic drinking water services, urban (% of urban population)    4.713805
People using at least basic sanitation services (% of population)                     1.010101
People using at least basic sanitation services, rural (% of rural population)        4.713805
People using at least basic sanitation services, urban  (% of urban population)       4.713805
latitude                                                                              0.000000
longitude                                                                             0.000000
geometry                                                                              0.000000
dtype: float64

In [16]:
# drop rows with missing values
malaria_final.dropna().shape

(528, 18)